/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'volodymyrd' at '29.10.14 21:08' with Gradle 2.0
 *
 * @author volodymyrd, @date 29.10.14 21:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
